[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

[scratchpads.term]
animation = "fromTop"
command = "alacritty"
class = "Alacritty"
lazy = true
size = "99% 95%"
excludes = "*"

